//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGToolkitDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public class TestData
    {
        public double FretAmount { get; set; }
        public double ScaleLength { get; set; }
    }
}
